export const ROUTES = {
  HOME: "/",
  MALE: "/malecatalog",
  FEMALE: "/femalecatalog",
  BRANDS: "/brands",
  CATALOG: "/catalog",
  NEWBRANDS: "/newbrands",
  SALES: "/sales",
  ACCOUNT: "/account",
  SHOPCART: "/shopcart",
  SUPPORT: "/support",
  CONDITIONS: "/conditions",
  GUARANTEE: "/guarantee",
  POLICY: "/policy",
  DELIVERY: "/delivery",
};
