export const ROUTES = {
  HOME: "/",
  MALE: "/malecatalog",
  FEMALE: "/femalecatalog",
  BRANDS: "/brands",
  CATALOG: "/catalog",
  NEWBRANDS: "/newbrands",
  SALES: "/sales",
  ACCOUNT: "/account",
  SHOPCART: "/shopcart",
  ORDERHISTORY: "/orderhistory",
  FAVORITES: "/favorites",
  WALLET: "/wallet",
  SUPPORT: "/support",

  CONDITIONS: "/conditions",
  GUARANTEE: "/guarantee",
  POLICY: "/policy",
  DELIVERY: "/delivery",
};
